export const DATA_AVAILABLE = 'DATA_AVAILABLE';
export const ADD_FAVORITE = 'ADD_FAVORITE';
export const DELETE_PLACE = 'DELETE_PLACE';
export const SELECT_PLACE = 'SELECT_PLACE';
export const DESELECT_PLACE = 'DESELECT_PLACE';

